version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: keycloakdb
    ports:
      - 5432:5432

  keycloak:
    build:
      context: .
      dockerfile: keycloak/Dockerfile
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 8015:8080
